# Generated by Django 5.1.2 on 2024-11-20 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="country",
            field=models.CharField(blank=True, max_length=50, verbose_name="Страна проживания"),
        ),
    ]
