# Generated by Django 5.1.2 on 2024-10-28 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "header",
                    models.CharField(help_text="Введите название заголовка", max_length=150, verbose_name="Заголовок"),
                ),
                ("content", models.TextField(help_text="Наполните статью содержимым", verbose_name="Содержание")),
                (
                    "picture",
                    models.ImageField(blank=True, null=True, upload_to="blogs/photos/", verbose_name="Изображение"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("number_of_views", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Статья",
                "verbose_name_plural": "Статьи",
            },
        ),
    ]
