# Generated by Django 5.1.2 on 2024-10-28 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                help_text="Выберите предложенную категорию",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="catalog.category",
                verbose_name="Категория",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.CharField(help_text="Введите описание", max_length=500, null=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(help_text="Введите название продукта", max_length=150, verbose_name="Наименование"),
        ),
        migrations.AlterField(
            model_name="product",
            name="picture",
            field=models.ImageField(blank=True, null=True, upload_to="catalog/photos/", verbose_name="Изображение"),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, help_text="Введите цену", max_digits=10, verbose_name="Цена"),
        ),
        migrations.AlterField(
            model_name="product",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
